-- ============================================================================
-- XTROVERT — production integration (CURRENT LIVE STATE, regenerated by
-- reading the actual database directly — every table, policy, grant, and
-- function below was verified against production, not reconstructed from
-- memory). Safe to re-run: every statement is idempotent.
--
-- Run supabase/schema.sql FIRST (ranks + profiles), then this file.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) DAILY QUOTES — server-curated only. RLS is enabled with ZERO policies,
--    meaning no role (not even authenticated) can query this table directly
--    at all. The ONLY way to read a quote is get_daily_quote() below, which
--    is SECURITY DEFINER and bypasses RLS deliberately, on purpose, as the
--    single controlled door in. Nobody can INSERT/UPDATE/DELETE a quote from
--    the client under any circumstances.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_quotes (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_text  text NOT NULL CHECK (length(btrim(quote_text)) > 0),
  author      text NOT NULL DEFAULT 'Field Doctrine',
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.daily_quotes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.daily_quotes FROM anon, authenticated;
-- Intentionally NO policies of any kind on this table.

-- ----------------------------------------------------------------------------
-- 2) CHALLENGES — read-only for logged-in users, writable only by you
--    (service_role / SQL editor).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.challenges (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title          text NOT NULL,
  description    text NOT NULL,
  difficulty     text NOT NULL DEFAULT 'Medium',
  xp_reward      integer NOT NULL DEFAULT 50,
  required_rank  text NOT NULL DEFAULT 'Starter',
  is_active      boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.challenges FROM anon, authenticated;
GRANT SELECT ON public.challenges TO authenticated;

DROP POLICY IF EXISTS "Active challenges are viewable by authenticated users" ON public.challenges;
CREATE POLICY "Active challenges are viewable by authenticated users"
  ON public.challenges
  FOR SELECT
  TO authenticated
  USING (is_active = true);
-- No INSERT/UPDATE/DELETE policy or grant -> clients cannot add/edit challenges.

-- ----------------------------------------------------------------------------
-- 3) USER_COMPLETED_CHALLENGES — history of completions. Read-only for the
--    client; the only path that ever writes a row is complete_challenge().
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_completed_challenges (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  challenge_id  uuid NOT NULL REFERENCES public.challenges (id) ON DELETE CASCADE,
  xp_awarded    integer NOT NULL,
  completed_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, challenge_id)
);

ALTER TABLE public.user_completed_challenges ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_completed_challenges FROM anon, authenticated;
GRANT SELECT ON public.user_completed_challenges TO authenticated;
-- Deliberately NO insert grant — even though a defensive RLS policy exists
-- below in case grants are ever loosened by mistake, the current live grant
-- set already makes direct inserts impossible. complete_challenge() is the
-- only writer (it runs as the function owner, not as your role).

DROP POLICY IF EXISTS "Users can view own completions" ON public.user_completed_challenges;
CREATE POLICY "Users can view own completions"
  ON public.user_completed_challenges
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 4) JOURNAL_ENTRIES — strictly private. Read-only for the client; the only
--    writers are add_journal_entry() (free-form) and complete_challenge()
--    (challenge-linked). No direct INSERT grant exists.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.journal_entries (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  challenge_id    uuid REFERENCES public.challenges (id) ON DELETE SET NULL,
  content         text NOT NULL,
  title           text,
  is_broadcasted  boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.journal_entries FROM anon, authenticated;
GRANT SELECT ON public.journal_entries TO authenticated;

DROP POLICY IF EXISTS "Users manage own journals" ON public.journal_entries;
CREATE POLICY "Users manage own journals"
  ON public.journal_entries
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 5) COMMUNITY_POSTS — publicly viewable; only the author can create their
--    own post. Like/reply/view counts are computed on read (not stored
--    columns), so there is nothing to desync or tamper with here.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.community_posts (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  journal_entry_id   uuid REFERENCES public.journal_entries (id) ON DELETE SET NULL,
  title              text NOT NULL,
  content            text NOT NULL,
  -- Optional public tag, one of a fixed set enforced below by a CHECK
  -- constraint — a raw API call with an arbitrary tag string is rejected by
  -- Postgres itself, not by client-side validation.
  tag                text,
  view_count         integer NOT NULL DEFAULT 0,
  created_at         timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.community_posts DROP CONSTRAINT IF EXISTS community_posts_tag_check;
ALTER TABLE public.community_posts ADD CONSTRAINT community_posts_tag_check
  CHECK (
    tag IS NULL OR tag IN (
      'Success Stories', 'Struggling', 'Motivation', 'Advice',
      'Question', 'Milestone', 'Accountability', 'Mental Health'
    )
  );

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.community_posts FROM anon, authenticated;
GRANT SELECT, INSERT ON public.community_posts TO authenticated;

DROP POLICY IF EXISTS "View community posts" ON public.community_posts;
CREATE POLICY "View community posts"
  ON public.community_posts
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Create own community posts" ON public.community_posts;
CREATE POLICY "Create own community posts"
  ON public.community_posts
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);
-- No UPDATE/DELETE -> posts cannot be edited or removed by anyone, including
-- their author, from the client (matches immutable "field report" design).

-- ----------------------------------------------------------------------------
-- 6) POST_LIKES / POST_REPLIES / POST_VIEWS — low-risk social actions;
--    users may only ever act as themselves.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.post_likes (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id     uuid NOT NULL REFERENCES public.community_posts (id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (post_id, user_id)
);

ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_likes TO authenticated;

DROP POLICY IF EXISTS "View post likes" ON public.post_likes;
CREATE POLICY "View post likes" ON public.post_likes FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Manage own post likes" ON public.post_likes;
CREATE POLICY "Manage own post likes"
  ON public.post_likes FOR ALL TO authenticated USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.post_replies (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id     uuid NOT NULL REFERENCES public.community_posts (id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  content     text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.post_replies ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_replies TO authenticated;

DROP POLICY IF EXISTS "View post replies" ON public.post_replies;
CREATE POLICY "View post replies" ON public.post_replies FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Manage own post replies" ON public.post_replies;
CREATE POLICY "Manage own post replies"
  ON public.post_replies FOR ALL TO authenticated USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.post_views (
  post_id     uuid NOT NULL REFERENCES public.community_posts (id) ON DELETE CASCADE,
  viewer_id   uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
  PRIMARY KEY (post_id, viewer_id)
);

ALTER TABLE public.post_views ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_views TO authenticated;

DROP POLICY IF EXISTS "Users manage own post views" ON public.post_views;
CREATE POLICY "Users manage own post views"
  ON public.post_views FOR ALL TO authenticated USING (auth.uid() = viewer_id) WITH CHECK (auth.uid() = viewer_id);

-- ----------------------------------------------------------------------------
-- 7) BLOCKED_USERS / CONTENT_REPORTS — moderation & safety.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blocked_users (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  blocker_id  uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  blocked_id  uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (blocker_id, blocked_id)
);

ALTER TABLE public.blocked_users ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.blocked_users TO authenticated;

DROP POLICY IF EXISTS "Manage own blocks" ON public.blocked_users;
CREATE POLICY "Manage own blocks"
  ON public.blocked_users FOR ALL TO authenticated USING (auth.uid() = blocker_id);

CREATE TABLE IF NOT EXISTS public.content_reports (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id        uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  reported_user_id   uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  post_id            uuid REFERENCES public.community_posts (id) ON DELETE CASCADE,
  reason             text NOT NULL,
  status             text NOT NULL DEFAULT 'pending',
  created_at         timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.content_reports ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.content_reports TO authenticated;

DROP POLICY IF EXISTS "Submit content reports" ON public.content_reports;
CREATE POLICY "Submit content reports"
  ON public.content_reports FOR INSERT TO authenticated WITH CHECK (auth.uid() = reporter_id);
-- No SELECT policy for regular users -> reports are write-only from the
-- client; only you (service_role in the dashboard) can review them.

-- ----------------------------------------------------------------------------
-- 7b) ANTI-SPAM — BEFORE INSERT triggers on community_posts, post_replies,
--     and messages. These run in the database itself, so they apply no
--     matter what makes the insert call (the app, a future RPC, or someone
--     hitting the REST API directly with a script). RLS above controls WHO
--     can write; these triggers control WHAT and HOW OFTEN.
--       - community_posts: title >= 3 chars, content >= 20 chars,
--         15s cooldown per user. (15s is intentionally below
--         complete_challenge()'s own 20s cooldown so a normal broadcast
--         posted via a challenge completion can never be blocked by this.)
--       - post_replies: content >= 10 chars, 8s cooldown per user
--         (applies even when replying to your own post).
--       - messages: non-empty, <= 2000 chars, 2s cooldown per user across
--         every conversation (1:1 and group).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_post_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  last_post_at timestamptz;
BEGIN
  IF length(btrim(coalesce(NEW.title, ''))) < 3 THEN
    RAISE EXCEPTION 'Post title must be at least 3 characters';
  END IF;
  IF length(btrim(coalesce(NEW.content, ''))) < 20 THEN
    RAISE EXCEPTION 'Post must be at least 20 characters';
  END IF;

  SELECT max(created_at) INTO last_post_at
  FROM public.community_posts
  WHERE user_id = NEW.user_id;

  IF last_post_at IS NOT NULL AND last_post_at > now() - interval '15 seconds' THEN
    RAISE EXCEPTION 'Please wait a moment before posting again';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_post_rules ON public.community_posts;
CREATE TRIGGER trg_enforce_post_rules
  BEFORE INSERT ON public.community_posts
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_post_rules();
-- Trigger functions are invoked by the trigger mechanism itself, never by a
-- direct call — revoke EXECUTE so PostgREST doesn't expose a pointless (and
-- broken outside trigger context) /rest/v1/rpc/enforce_post_rules endpoint.
REVOKE ALL ON FUNCTION public.enforce_post_rules() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.enforce_reply_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  last_reply_at timestamptz;
BEGIN
  IF length(btrim(coalesce(NEW.content, ''))) < 10 THEN
    RAISE EXCEPTION 'Reply must be at least 10 characters';
  END IF;

  SELECT max(created_at) INTO last_reply_at
  FROM public.post_replies
  WHERE user_id = NEW.user_id;

  IF last_reply_at IS NOT NULL AND last_reply_at > now() - interval '8 seconds' THEN
    RAISE EXCEPTION 'Please wait a moment before replying again';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_reply_rules ON public.post_replies;
CREATE TRIGGER trg_enforce_reply_rules
  BEFORE INSERT ON public.post_replies
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_reply_rules();
REVOKE ALL ON FUNCTION public.enforce_reply_rules() FROM PUBLIC, anon, authenticated;

-- ----------------------------------------------------------------------------
-- 8) STREAK_DAYS — weekday tracker source of truth. Read-only for the owner;
--    the only writer is complete_challenge().
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.streak_days (
  user_id        uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  activity_date  date NOT NULL,
  PRIMARY KEY (user_id, activity_date)
);

ALTER TABLE public.streak_days ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.streak_days FROM anon, authenticated;
GRANT SELECT ON public.streak_days TO authenticated;

DROP POLICY IF EXISTS "Users view own streak days" ON public.streak_days;
CREATE POLICY "Users view own streak days"
  ON public.streak_days FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 9) MESSAGING — conversations / conversation_members / messages.
--    conversations + conversation_members have NO direct insert grant at
--    all: the only way to create either is find_or_create_direct_conversation()
--    or create_group_conversation(). messages allows INSERT (sending) and
--    SELECT (reading) only — no UPDATE/DELETE, so nothing can be edited or
--    unsent once posted.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversations (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  is_group    boolean NOT NULL DEFAULT false,
  title       text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversation_members (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id   uuid NOT NULL REFERENCES public.conversations (id) ON DELETE CASCADE,
  user_id           uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  joined_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id   uuid NOT NULL REFERENCES public.conversations (id) ON DELETE CASCADE,
  sender_id         uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  content           text NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- Anti-spam: non-empty, capped length, and a 2s per-user cooldown across
-- every conversation (1:1 and group). See section 7b for community_posts /
-- post_replies triggers of the same kind.
CREATE OR REPLACE FUNCTION public.enforce_message_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  last_msg_at timestamptz;
BEGIN
  IF length(btrim(coalesce(NEW.content, ''))) < 1 THEN
    RAISE EXCEPTION 'Message cannot be empty';
  END IF;
  IF length(NEW.content) > 2000 THEN
    RAISE EXCEPTION 'Message is too long';
  END IF;

  SELECT max(created_at) INTO last_msg_at
  FROM public.messages
  WHERE sender_id = NEW.sender_id;

  IF last_msg_at IS NOT NULL AND last_msg_at > now() - interval '2 seconds' THEN
    RAISE EXCEPTION 'You are sending messages too quickly';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_message_rules ON public.messages;
CREATE TRIGGER trg_enforce_message_rules
  BEFORE INSERT ON public.messages
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_message_rules();
REVOKE ALL ON FUNCTION public.enforce_message_rules() FROM PUBLIC, anon, authenticated;

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.conversations FROM anon, authenticated;
REVOKE ALL ON public.conversation_members FROM anon, authenticated;
REVOKE ALL ON public.messages FROM anon, authenticated;
GRANT SELECT ON public.conversations TO authenticated;
GRANT SELECT ON public.conversation_members TO authenticated;
GRANT SELECT, INSERT ON public.messages TO authenticated;

-- is_conversation_member() is SECURITY DEFINER on purpose: it lets the
-- policies below check membership WITHOUT the policies recursively querying
-- the very table they're protecting (which caused infinite-recursion errors
-- before this fix).
CREATE OR REPLACE FUNCTION public.is_conversation_member(p_conversation_id uuid, p_user_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.conversation_members
    WHERE conversation_id = p_conversation_id AND user_id = p_user_id
  );
$$;
REVOKE ALL ON FUNCTION public.is_conversation_member(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_conversation_member(uuid, uuid) TO authenticated;

DROP POLICY IF EXISTS "Members view conversations" ON public.conversations;
CREATE POLICY "Members view conversations"
  ON public.conversations FOR SELECT TO authenticated
  USING (public.is_conversation_member(id, auth.uid()));

DROP POLICY IF EXISTS "Members view list" ON public.conversation_members;
CREATE POLICY "Members view list"
  ON public.conversation_members FOR SELECT TO authenticated
  USING (public.is_conversation_member(conversation_id, auth.uid()));

DROP POLICY IF EXISTS "Members manage messages" ON public.messages;
CREATE POLICY "Members manage messages"
  ON public.messages FOR ALL TO authenticated
  USING (public.is_conversation_member(conversation_id, auth.uid()))
  WITH CHECK (public.is_conversation_member(conversation_id, auth.uid()) AND sender_id = auth.uid());

-- ============================================================================
-- SERVER-SIDE FUNCTIONS (the only doors into every sensitive table above)
-- ============================================================================

-- ---- register_daily_login(): LOGIN ONLY. Does not touch streak_count or
-- social_score at all — those are exclusively earned via complete_challenge().
CREATE OR REPLACE FUNCTION public.register_daily_login()
RETURNS public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid         uuid := auth.uid();
  profile_row public.profiles;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  UPDATE public.profiles
  SET last_login_date = timezone('utc', now())
  WHERE id = uid
  RETURNING * INTO profile_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile not found for user %', uid;
  END IF;

  RETURN profile_row;
END;
$$;
REVOKE ALL ON FUNCTION public.register_daily_login() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.register_daily_login() TO authenticated;

-- ---- evaluate_rank_on_score_change(): auto rank-up trigger on profiles.
CREATE OR REPLACE FUNCTION public.evaluate_rank_on_score_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  next_rank_title text;
BEGIN
  IF TG_OP = 'INSERT' OR NEW.social_score IS DISTINCT FROM OLD.social_score THEN
    SELECT r.title INTO next_rank_title
    FROM public.ranks r
    WHERE r.xp_required <= NEW.social_score
    ORDER BY r.xp_required DESC
    LIMIT 1;

    IF next_rank_title IS NOT NULL THEN
      NEW.rank_title := next_rank_title;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_rank_up ON public.profiles;
CREATE TRIGGER trg_profiles_rank_up
  BEFORE INSERT OR UPDATE OF social_score ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.evaluate_rank_on_score_change();

-- ---- get_my_profile(): the ONLY way to read your own full record (score,
-- streak, cooldown timestamps) — raw SELECTs on profiles cannot see these.
CREATE OR REPLACE FUNCTION public.get_my_profile()
RETURNS TABLE(
  username text, bio text, rank_title text, social_score integer, streak_count integer,
  last_username_change_at timestamptz, last_bio_change_at timestamptz
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.username, p.bio, p.rank_title, p.social_score, p.streak_count,
         p.last_username_change_at, p.last_bio_change_at
  FROM public.profiles p
  WHERE p.id = auth.uid();
$$;
REVOKE ALL ON FUNCTION public.get_my_profile() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_profile() TO authenticated;

-- ---- update_username(): 7-day cooldown, letters/digits/spaces only,
-- duplicates allowed (id is the real identity), no-op on unchanged value.
CREATE OR REPLACE FUNCTION public.update_username(p_new_username text)
RETURNS public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid     uuid := auth.uid();
  v_clean text := btrim(p_new_username);
  v_row   public.profiles;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF v_clean IS NULL OR length(v_clean) < 3 OR length(v_clean) > 20 THEN
    RAISE EXCEPTION 'Username must be 3-20 characters';
  END IF;
  IF v_clean !~ '^[A-Za-z0-9 ]+$' THEN
    RAISE EXCEPTION 'Username may only contain letters, numbers, and spaces';
  END IF;

  SELECT * INTO v_row FROM public.profiles WHERE id = uid FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;

  IF v_row.username = v_clean THEN
    RETURN v_row;
  END IF;

  IF v_row.last_username_change_at IS NOT NULL
     AND v_row.last_username_change_at > now() - interval '7 days' THEN
    RAISE EXCEPTION 'Username can be changed again on %',
      to_char(v_row.last_username_change_at + interval '7 days', 'YYYY-MM-DD');
  END IF;

  UPDATE public.profiles
  SET username = v_clean, last_username_change_at = now()
  WHERE id = uid
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;
REVOKE ALL ON FUNCTION public.update_username(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_username(text) TO authenticated;

-- ---- update_bio(): 1-day cooldown, 220 char cap, no-op on unchanged value.
CREATE OR REPLACE FUNCTION public.update_bio(p_new_bio text)
RETURNS public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid     uuid := auth.uid();
  v_clean text := btrim(COALESCE(p_new_bio, ''));
  v_row   public.profiles;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF length(v_clean) > 220 THEN
    RAISE EXCEPTION 'Bio must be 220 characters or fewer';
  END IF;

  SELECT * INTO v_row FROM public.profiles WHERE id = uid FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile not found';
  END IF;

  IF v_row.bio = v_clean THEN
    RETURN v_row;
  END IF;

  IF v_row.last_bio_change_at IS NOT NULL
     AND v_row.last_bio_change_at > now() - interval '1 day' THEN
    RAISE EXCEPTION 'Bio can be changed again on %',
      to_char(v_row.last_bio_change_at + interval '1 day', 'YYYY-MM-DD HH24:MI');
  END IF;

  UPDATE public.profiles
  SET bio = v_clean, last_bio_change_at = now()
  WHERE id = uid
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;
REVOKE ALL ON FUNCTION public.update_bio(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_bio(text) TO authenticated;

-- ---- get_daily_quote(): deterministic same-quote-all-day rotation. The
-- only possible read path into daily_quotes (see section 1 above).
CREATE OR REPLACE FUNCTION public.get_daily_quote()
RETURNS TABLE(quote_text text, author text)
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  WITH ranked AS (
    SELECT q.quote_text, q.author,
           row_number() OVER (ORDER BY q.created_at, q.id) - 1 AS rn,
           count(*) OVER () AS total
    FROM public.daily_quotes q
    WHERE q.is_active = true
  )
  SELECT quote_text, author FROM ranked
  WHERE total > 0 AND rn = (CURRENT_DATE - DATE '2024-01-01') % total;
$$;
REVOKE ALL ON FUNCTION public.get_daily_quote() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_daily_quote() TO authenticated;

-- ---- add_journal_entry(): free-form private journal entry, no challenge
-- required. Server-validated length + a 15s cooldown (checked against the
-- most recent journal_entries row for this user, regardless of whether it
-- came from this function or complete_challenge() — closes the loophole of
-- alternating between the two to bypass either one's own cooldown). The
-- ONLY insert paths into journal_entries are this function and
-- complete_challenge().
CREATE OR REPLACE FUNCTION public.add_journal_entry(p_content text, p_title text DEFAULT NULL)
RETURNS public.journal_entries
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid           uuid := auth.uid();
  v_clean       text := btrim(p_content);
  v_title       text := nullif(btrim(coalesce(p_title, '')), '');
  v_row         public.journal_entries;
  last_entry_at timestamptz;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF v_clean IS NULL OR length(v_clean) < 60 THEN
    RAISE EXCEPTION 'Journal entry too short (min 60 chars)';
  END IF;
  IF length(v_clean) > 4000 THEN
    RAISE EXCEPTION 'Journal entry too long';
  END IF;
  IF v_title IS NOT NULL AND length(v_title) > 80 THEN
    RAISE EXCEPTION 'Title too long (max 80 chars)';
  END IF;

  SELECT max(created_at) INTO last_entry_at
  FROM public.journal_entries
  WHERE user_id = uid;

  IF last_entry_at IS NOT NULL AND last_entry_at > now() - interval '15 seconds' THEN
    RAISE EXCEPTION 'Please wait a moment before adding another entry';
  END IF;

  INSERT INTO public.journal_entries (user_id, challenge_id, content, title, is_broadcasted)
  VALUES (uid, NULL, v_clean, v_title, false)
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;
REVOKE ALL ON FUNCTION public.add_journal_entry(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.add_journal_entry(text, text) TO authenticated;

-- ---- increment_post_view(): dedupes via post_views (post_id, viewer_id)
-- primary key, so the same viewer can never inflate a post's count twice.
CREATE OR REPLACE FUNCTION public.increment_post_view(p_post_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid          uuid := auth.uid();
  v_rows       integer := 0;
  v_view_count integer;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  INSERT INTO public.post_views (post_id, viewer_id)
  VALUES (p_post_id, uid)
  ON CONFLICT (post_id, viewer_id) DO NOTHING;

  GET DIAGNOSTICS v_rows = ROW_COUNT;

  IF v_rows > 0 THEN
    UPDATE public.community_posts
    SET view_count = COALESCE(view_count, 0) + 1
    WHERE id = p_post_id
    RETURNING view_count INTO v_view_count;
  ELSE
    SELECT view_count INTO v_view_count FROM public.community_posts WHERE id = p_post_id;
  END IF;

  RETURN COALESCE(v_view_count, 0);
END;
$$;
REVOKE ALL ON FUNCTION public.increment_post_view(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_post_view(uuid) TO authenticated;

-- ---- complete_challenge(): THE atomic core. Validates journal length,
-- enforces a 20-second cooldown between completions, awards XP read from
-- the challenge row itself (never trusts the client), only bumps
-- streak_count on the FIRST completion of the local calendar day, and
-- optionally broadcasts to the community feed — all in one transaction.
-- NOTE: a too-short broadcast title (< 3 chars) falls back to 'Field
-- Report' rather than raising, so it can never trip community_posts'
-- own length trigger (section 7b) and roll back the whole completion.
CREATE OR REPLACE FUNCTION public.complete_challenge(
  p_challenge_id uuid,
  p_journal_text text,
  p_broadcast boolean DEFAULT false,
  p_post_title text DEFAULT NULL,
  p_local_date date DEFAULT NULL,
  p_journal_title text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid              uuid := auth.uid();
  profile_row      public.profiles;
  today_utc        date := (timezone('utc', now()))::date;
  effective_date   date;
  v_xp             integer := 0;
  v_journal_id     uuid;
  v_journal_title  text := nullif(btrim(coalesce(p_journal_title, '')), '');
  v_post_title     text;
  v_is_first_today boolean;
  v_new_streak     integer;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_journal_text IS NULL OR length(btrim(p_journal_text)) < 60 THEN
    RAISE EXCEPTION 'Journal entry too short (min 60 chars)';
  END IF;
  IF length(btrim(p_journal_text)) > 4000 THEN
    RAISE EXCEPTION 'Journal entry too long';
  END IF;
  IF v_journal_title IS NOT NULL AND length(v_journal_title) > 80 THEN
    RAISE EXCEPTION 'Title too long (max 80 chars)';
  END IF;

  IF p_local_date IS NULL OR p_local_date < (today_utc - 1) OR p_local_date > (today_utc + 1) THEN
    effective_date := today_utc;
  ELSE
    effective_date := p_local_date;
  END IF;

  SELECT * INTO profile_row FROM public.profiles WHERE id = uid FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile not found for user %', uid;
  END IF;

  IF profile_row.last_challenge_completed_at IS NOT NULL
     AND profile_row.last_challenge_completed_at > now() - interval '20 seconds' THEN
    RAISE EXCEPTION 'Please wait a moment before completing another challenge.';
  END IF;

  SELECT coalesce(c.xp_reward, 0) INTO v_xp FROM public.challenges c WHERE c.id = p_challenge_id;
  v_xp := coalesce(v_xp, 0);

  BEGIN
    INSERT INTO public.user_completed_challenges (user_id, challenge_id, xp_awarded)
    VALUES (uid, p_challenge_id, v_xp);
  EXCEPTION WHEN unique_violation THEN
    NULL;
  END;

  INSERT INTO public.journal_entries (user_id, challenge_id, content, title)
  VALUES (uid, p_challenge_id, btrim(p_journal_text), v_journal_title)
  RETURNING id INTO v_journal_id;

  IF p_broadcast THEN
    v_post_title := btrim(coalesce(p_post_title, ''));
    IF length(v_post_title) < 3 THEN
      v_post_title := 'Field Report';
    END IF;

    INSERT INTO public.community_posts (user_id, title, content, journal_entry_id)
    VALUES (uid, v_post_title, btrim(p_journal_text), v_journal_id);
  END IF;

  v_is_first_today := profile_row.last_streak_date IS DISTINCT FROM effective_date;

  IF v_is_first_today THEN
    IF profile_row.last_streak_date = (effective_date - 1) THEN
      v_new_streak := profile_row.streak_count + 1;
    ELSE
      v_new_streak := 1;
    END IF;
    INSERT INTO public.streak_days (user_id, activity_date) VALUES (uid, effective_date) ON CONFLICT DO NOTHING;
  ELSE
    v_new_streak := profile_row.streak_count;
  END IF;

  UPDATE public.profiles
  SET social_score = social_score + v_xp,
      streak_count = v_new_streak,
      last_streak_date = CASE WHEN v_is_first_today THEN effective_date ELSE last_streak_date END,
      last_challenge_completed_at = now()
  WHERE id = uid
  RETURNING * INTO profile_row;

  RETURN jsonb_build_object(
    'success', true,
    'xp_awarded', v_xp,
    'streak_count', profile_row.streak_count,
    'social_score', profile_row.social_score,
    'rank_title', profile_row.rank_title
  );
END;
$$;
REVOKE ALL ON FUNCTION public.complete_challenge(uuid, text, boolean, text, date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.complete_challenge(uuid, text, boolean, text, date, text) TO authenticated;

-- ---- find_or_create_direct_conversation(): the only way a 1:1 chat is created.
CREATE OR REPLACE FUNCTION public.find_or_create_direct_conversation(p_other_user uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid           uuid := auth.uid();
  convo         uuid;
  last_convo_at timestamptz;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF p_other_user IS NULL OR p_other_user = uid THEN
    RAISE EXCEPTION 'Invalid conversation target';
  END IF;

  SELECT cm.conversation_id INTO convo
  FROM public.conversation_members cm
  JOIN public.conversation_members other
    ON other.conversation_id = cm.conversation_id AND other.user_id = p_other_user
  WHERE cm.user_id = uid
  GROUP BY cm.conversation_id
  HAVING count(*) = (SELECT count(*) FROM public.conversation_members x WHERE x.conversation_id = cm.conversation_id)
     AND count(*) = 2
  LIMIT 1;

  IF convo IS NOT NULL THEN
    RETURN convo;
  END IF;

  -- Cooldown only applies to actually CREATING a new conversation — opening
  -- an existing one (the branch above) is unaffected, so normal messaging
  -- with people you already talk to is never slowed down. Checked against
  -- profiles.last_conversation_created_at, which only this function and
  -- create_group_conversation() ever update.
  SELECT last_conversation_created_at INTO last_convo_at FROM public.profiles WHERE id = uid;
  IF last_convo_at IS NOT NULL AND last_convo_at > now() - interval '10 seconds' THEN
    RAISE EXCEPTION 'Please wait a moment before starting another conversation';
  END IF;

  INSERT INTO public.conversations DEFAULT VALUES RETURNING id INTO convo;
  INSERT INTO public.conversation_members (conversation_id, user_id) VALUES (convo, uid), (convo, p_other_user);

  UPDATE public.profiles SET last_conversation_created_at = now() WHERE id = uid;

  RETURN convo;
END;
$$;
REVOKE ALL ON FUNCTION public.find_or_create_direct_conversation(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.find_or_create_direct_conversation(uuid) TO authenticated;

-- ---- create_group_conversation(): the only way a group chat is created.
-- Validates 1-19 other members, all must be real profiles, and enforces the
-- same 10s "new conversation" cooldown as find_or_create_direct_conversation
-- (shared via profiles.last_conversation_created_at) since this function
-- always creates a brand new conversation. anon explicitly has EXECUTE
-- revoked (Postgres auto-grants EXECUTE to PUBLIC by default on function
-- creation, which silently includes anon unless revoked here).
CREATE OR REPLACE FUNCTION public.create_group_conversation(p_member_ids uuid[], p_title text DEFAULT NULL)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  convo uuid;
  member uuid;
  members uuid[];
  found_count int;
  last_convo_at timestamptz;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_member_ids IS NULL OR array_length(p_member_ids, 1) IS NULL THEN
    RAISE EXCEPTION 'At least one other member is required';
  END IF;

  SELECT array_agg(DISTINCT m) INTO members FROM unnest(p_member_ids) AS m WHERE m IS NOT NULL AND m <> uid;

  IF members IS NULL OR array_length(members, 1) < 1 THEN
    RAISE EXCEPTION 'At least one other member is required';
  END IF;

  IF array_length(members, 1) > 19 THEN
    RAISE EXCEPTION 'Group chats are limited to 20 members';
  END IF;

  SELECT count(*) INTO found_count FROM public.profiles WHERE id = ANY(members);
  IF found_count <> array_length(members, 1) THEN
    RAISE EXCEPTION 'One or more selected users do not exist';
  END IF;

  SELECT last_conversation_created_at INTO last_convo_at FROM public.profiles WHERE id = uid FOR UPDATE;
  IF last_convo_at IS NOT NULL AND last_convo_at > now() - interval '10 seconds' THEN
    RAISE EXCEPTION 'Please wait a moment before starting another conversation';
  END IF;

  INSERT INTO public.conversations (is_group, title)
  VALUES (true, nullif(trim(coalesce(p_title, '')), ''))
  RETURNING id INTO convo;

  INSERT INTO public.conversation_members (conversation_id, user_id) VALUES (convo, uid);

  FOREACH member IN ARRAY members LOOP
    INSERT INTO public.conversation_members (conversation_id, user_id)
    VALUES (convo, member)
    ON CONFLICT (conversation_id, user_id) DO NOTHING;
  END LOOP;

  UPDATE public.profiles SET last_conversation_created_at = now() WHERE id = uid;

  RETURN convo;
END;
$$;
REVOKE ALL ON FUNCTION public.create_group_conversation(uuid[], text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_group_conversation(uuid[], text) TO authenticated;

-- ============================================================================
-- Done. This file mirrors the actual live database as of the date this file
-- was regenerated — every CREATE/GRANT/POLICY above was written by reading
-- the real, current definitions out of Supabase, not from memory.
-- ============================================================================
